`name: budget_tracker_app_d4
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.5
  get: ^4.7.2
  device_preview: ^1.2.0
  shared_preferences: ^2.5.3
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


`